In [1]:
import numpy as np
a=np.array([10,20,30])
print("One dimensional array:",a)


One dimensional array: [10 20 30]


In [2]:
import numpy as np
b=np.array([[1,2,3],[4,5,6]])
print("Two dimensional array:",b)

Two dimensional array: [[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Three dimensional array:",c)

Three dimensional array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
import numpy as np
d=np.zeros((3,5))
print("\n array with all zereos\n",d)



 array with all zereos
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
e=np.random.random((3,2))
print("\nrandom value:\n",e)


random value:
 [[0.36991328 0.16382894]
 [0.19645263 0.9125452 ]
 [0.37061954 0.99439656]]


In [7]:
import numpy as np
f=np.arange(10,30,5)
print("\n sequence array :\n",f)



 sequence array :
 [10 15 20 25]


In [4]:
import numpy as np
a=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
b=a.reshape(4,3)
print("\n old array :\n",a)
print("\n reshaped array:\n",b)



 old array :
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

 reshaped array:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [2]:
import numpy as np
a=np.zeros((5,3))
b=np.random.random((5,3))
c=np.arange(0,10,2)
d=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
e=arr.reshape(6,2)
print("Array with zeros:",a)
print("\n Array with random values:\n",b)
print("\n Array in step:\n",c)
print("\n Old array: \n",d)
print("\n Reshaped array:\n",e)

Array with zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 Array with random values:
 [[0.13539421 0.52204954 0.96892955]
 [0.79955324 0.35080834 0.19218304]
 [0.76212539 0.36333579 0.98150949]
 [0.28955575 0.92086973 0.71597759]
 [0.78937333 0.6411776  0.34775191]]

 Array in step:
 [0 2 4 6 8]

 Old array: 
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

 Reshaped array:
 [[1 2]
 [3 4]
 [5 2]
 [4 2]
 [1 2]
 [0 1]]


In [3]:
import numpy as np
flat=arr.flatten()
print("Flattened array:\n",flat)

Flattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [ ]:
print("\n")

In [5]:
#print type of element
import numpy as np
print("\n array of element type",arr.dtype)


 array of element type int32


In [8]:
#convert integer to float
newtype=arr.astype('f')
print("\n count array element:\n",newtype)
print("counted array:",newtype.dtype)


 count array element:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
counted array: float32


In [12]:
#detemine the size of the array
size=len(arr)
print("\n size of the array:\n",size)


 size of the array:
 3
