In [9]:
#slicing
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
print(slice1)

[3 4 5 6]


In [10]:
#slice with step og 2
slice2=arr[::2]
print(slice2)

[1 3 5 7 9]


In [11]:
#reversing
reverse=arr[::-1]
print(reverse)

[9 8 7 6 5 4 3 2 1]


In [12]:
slice=arr[1::5]
print(slice)

[2 7]


In [15]:
#slicing multidimenstional arrayrr=np.a
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
#slice row 0 to 2
#slice column 1 to 3
slice1=arr[0:2,1:3]
print(slice1)


[[2 3]
 [5 6]]


In [16]:
#extract the first column
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
col=arr[:,0]
print(col)

[1 4 7]


In [17]:
#extract second row
row2=arr[1,:]
print(row2)

[4 5 6]


In [19]:
 print(arr[1,2])

6


In [21]:
print(arr[-2])

[4 5 6]


In [23]:
 arr=np.array([10,20,30,45,67,89])
 print(arr[arr>25])

[30 45 67 89]


In [28]:
#horizontal joint
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [26]:
#vertical joint
result=np.vstack((arr1,arr2))
print(result)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [27]:
#depth joint
result=np.dstack((arr1,arr2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [29]:
#splitting in numpy
arr=np.array([1,2,3,4,5,6])
result=np.split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [30]:
#splitting in unequal parts
result=np.array_split(arr,4)
print(result)

[array([1, 2]), array([3, 4]), array([5]), array([6])]
